region                = "us-east-1"
instance_type_web     = "t3.micro"
instance_type_db      = "t3.small"
instance_type_bastion = "t3.micro"
key_pair_name         = "techcorp-key"
my_ip                 = "129.222.206.39/32"